trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/python/functions/func_trigger
    - src/python/common

variables:
- group: waldo-staging

pool:
  vmImage: ubuntu-latest

steps:
  - template: func-trigger-deploy-steps.yaml
    parameters:
      core_function_trigger_name: $(core_function_trigger_name)
