trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/python/common

pool:
  vmImage: ubuntu-latest

variables:
  commonDirectory: common
  pythonDirectory: $(Build.SourcesDirectory)/src/python

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9"
      architecture: "x64"

  - bash: |
      pip install -r requirements-dev.txt
      pip install -r $(commonDirectory)/requirements.txt
    displayName: Install prerequisites
    workingDirectory: $(pythonDirectory)

  - bash: |
      python -m flake8
    displayName: Run flake8 $(commonDirectory)
    workingDirectory: $(pythonDirectory)

  - bash: |
      python -m pytest --junitxml=./test-results.xml $(commonDirectory)
    displayName: Run tests
    workingDirectory: $(pythonDirectory)
